source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
name: Zhan Zhuang
description: A Arte do Cultivo da Quietude
url: http://chikung.in

safe: true
lsi: false
pygments: true
