source:      .
destination: ~/blogs/chikung
plugins:     ./_plugins
posts: 	     ./_posts
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
markdown: kramdown
name: Zhan Zhuang
description: A Arte do Cultivo da Quietude
url: http://chikung.in
safe: true
lsi: false
pygments: true
